# Generated by Django 4.1.7 on 2023-04-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sovchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('age', models.IntegerField(default=18)),
                ('cell_phone', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('hobby', models.TextField()),
                ('study', models.CharField(max_length=255)),
                ('work_salary', models.CharField(max_length=255)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('gender', models.CharField(choices=[('e', 'erkak'), ('a', 'ayol')], max_length=15)),
            ],
        ),
    ]
